spring:
  datasource:
    username: xmc
    password: 294207
    url: jdbc:mysql://192.168.3.21:3306/gulimarket_ums
    driver-class-name: com.mysql.jdbc.Driver
  #nacos注册中心配置
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimarket-member

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 8000